let stream=null,facingMode='user',latestGesture='Waiting...',hands=null,running=false;
const tamil={HELLO:'வணக்கம்',YES:'ஆம்',NO:'இல்லை',STOP:'நிறுத்து','I LOVE YOU':'நான் உன்னை நேசிக்கிறேன்','THANK YOU':'நன்றி'};
const signs={hello:'👋',yes:'👍',no:'👎','thank you':'🙏',help:'🆘','i love you':'🤟',please:'🙏',more:'🤲',stop:'✋','all done':'🙌',good:'👍',bad:'👎',love:'❤️',friend:'🤝',family:'👨‍👩‍👧',mother:'👩',father:'👨',brother:'👦',sister:'👧',boy:'👦',girl:'👧',eat:'🍴',drink:'🥤',water:'💧',food:'🍽️',home:'🏠',school:'🏫',college:'🎓',understand:'💡',wait:'⏳'};
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));const n={home:0,camera:1,upload:2,text:3}[id];document.querySelectorAll('.nav')[n]?.classList.add('active')}
function changeLanguage(){if(document.getElementById('languageSelect').value==='ta')document.getElementById('tamilResult').innerText=tamil[latestGesture]||'';else document.getElementById('tamilResult').innerText=''}
async function startCamera(){stopCamera();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode},audio:false});let v=document.getElementById('cameraVideo');v.srcObject=stream;await v.play();running=true;initHands();processVideo()}catch(e){alert('Camera permission is required.')}}
function stopCamera(){running=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}document.getElementById('cameraVideo').srcObject=null}
function switchCamera(){facingMode=facingMode==='user'?'environment':'user';if(running)startCamera()}
function initHands(){if(typeof Hands==='undefined')return;hands=new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});hands.setOptions({maxNumHands:2,modelComplexity:1,minDetectionConfidence:.5,minTrackingConfidence:.5});hands.onResults(results)}
async function processVideo(){if(!running||!hands)return;let v=document.getElementById('cameraVideo');if(v.readyState>=2)await hands.send({image:v});requestAnimationFrame(processVideo)}
function results(r){let c=document.getElementById('cameraCanvas'),v=document.getElementById('cameraVideo'),x=c.getContext('2d');c.width=v.videoWidth||v.clientWidth;c.height=v.videoHeight||v.clientHeight;x.clearRect(0,0,c.width,c.height);if(r.multiHandLandmarks?.length){r.multiHandLandmarks.forEach(l=>{if(typeof drawConnectors!=='undefined'){drawConnectors(x,l,HAND_CONNECTIONS,{color:'#fff',lineWidth:2});drawLandmarks(x,l,{color:'#ffdd00',lineWidth:1})}});let g=classify(r.multiHandLandmarks[0]);if(g)setGesture(g)}}
function ext(l,t,p){return l[t].y<l[p].y}function classify(l){if(!l)return null;let i=ext(l,8,6),m=ext(l,12,10),r=ext(l,16,14),p=ext(l,20,18);if(!i&&!m&&!r&&!p)return'YES';if(i&&m&&r&&p)return'STOP';if(i&&m&&!r&&!p)return'NO';if(i&&!m&&!r&&p)return'I LOVE YOU';return null}
function setGesture(g){latestGesture=g;document.getElementById('gestureResult').innerText=g;document.getElementById('tamilResult').innerText=document.getElementById('languageSelect').value==='ta'?(tamil[g]||''):'';document.getElementById('confidence').innerText='Confidence: Detected'}
function speakResult(){speakText(document.getElementById('languageSelect').value==='ta'?(tamil[latestGesture]||latestGesture):latestGesture)}
function speakText(t){if(!t||!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang=document.getElementById('languageSelect').value==='ta'?'ta-IN':'en-IN';speechSynthesis.speak(u)}
function handleVideoUpload(e){let f=e.target.files[0];if(!f)return;document.getElementById('uploadedVideo').src=URL.createObjectURL(f);document.getElementById('videoResult').innerText='Video loaded. AI video recognition can be connected here.'}
function textToSign(){let t=document.getElementById('textInput').value.toLowerCase().trim();document.getElementById('signOutput').innerText=t?t.split(/\s+/).map(w=>signs[w.replace(/[^a-z]/g,'')]||'🤟').join(' '):'Please enter some text.'}
function startVoiceInput(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Voice recognition is not supported in this browser.');return}let r=new R();r.lang=document.getElementById('languageSelect').value==='ta'?'ta-IN':'en-IN';r.onresult=e=>document.getElementById('textInput').value=e.results[0][0].transcript;r.start()}

